//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class SLSC {
    
    private SLSCFPGAConfiguration fPGAConfigurationField;
    
    private SLSCSPIConfiguration sPIConfigurationField;
    
    private SLSCModule[] modulesField;
    
    /// <remarks/>
    public SLSCFPGAConfiguration FPGAConfiguration {
        get {
            return this.fPGAConfigurationField;
        }
        set {
            this.fPGAConfigurationField = value;
        }
    }
    
    /// <remarks/>
    public SLSCSPIConfiguration SPIConfiguration {
        get {
            return this.sPIConfigurationField;
        }
        set {
            this.sPIConfigurationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Module", IsNullable=false)]
    public SLSCModule[] Modules {
        get {
            return this.modulesField;
        }
        set {
            this.modulesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SLSCFPGAConfiguration {
    
    private string rIODeviceAddressField;
    
    private string pathField;
    
    private ushort fPGALoadDelayField;
    
    /// <remarks/>
    public string RIODeviceAddress {
        get {
            return this.rIODeviceAddressField;
        }
        set {
            this.rIODeviceAddressField = value;
        }
    }
    
    /// <remarks/>
    public string Path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
    
    /// <remarks/>
    public ushort FPGALoadDelay {
        get {
            return this.fPGALoadDelayField;
        }
        set {
            this.fPGALoadDelayField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SLSCSPIConfiguration {
    
    private ushort sPIDivideValueField;
    
    private uint sampleRateField;
    
    /// <remarks/>
    public ushort SPIDivideValue {
        get {
            return this.sPIDivideValueField;
        }
        set {
            this.sPIDivideValueField = value;
        }
    }
    
    /// <remarks/>
    public uint SampleRate {
        get {
            return this.sampleRateField;
        }
        set {
            this.sampleRateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SLSCModule {
    
    private string nameField;
    
    private string typeField;
    
    private byte rackField;
    
    private byte slotField;
    
    private byte dIOLineConfig0Field;
    
    private bool dIOLineConfig0FieldSpecified;
    
    private byte dIOLineConfig1Field;
    
    private bool dIOLineConfig1FieldSpecified;
    
    private byte dIOLineConfig2Field;
    
    private bool dIOLineConfig2FieldSpecified;
    
    private byte dIOLineConfig3Field;
    
    private bool dIOLineConfig3FieldSpecified;
    
    private uint hardwareSettlingTimeField;
    
    private bool hardwareSettlingTimeFieldSpecified;
    
    private SLSCModuleChannel[] channelsField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public byte Rack {
        get {
            return this.rackField;
        }
        set {
            this.rackField = value;
        }
    }
    
    /// <remarks/>
    public byte Slot {
        get {
            return this.slotField;
        }
        set {
            this.slotField = value;
        }
    }
    
    /// <remarks/>
    public byte DIOLineConfig0 {
        get {
            return this.dIOLineConfig0Field;
        }
        set {
            this.dIOLineConfig0Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DIOLineConfig0Specified {
        get {
            return this.dIOLineConfig0FieldSpecified;
        }
        set {
            this.dIOLineConfig0FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte DIOLineConfig1 {
        get {
            return this.dIOLineConfig1Field;
        }
        set {
            this.dIOLineConfig1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DIOLineConfig1Specified {
        get {
            return this.dIOLineConfig1FieldSpecified;
        }
        set {
            this.dIOLineConfig1FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte DIOLineConfig2 {
        get {
            return this.dIOLineConfig2Field;
        }
        set {
            this.dIOLineConfig2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DIOLineConfig2Specified {
        get {
            return this.dIOLineConfig2FieldSpecified;
        }
        set {
            this.dIOLineConfig2FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte DIOLineConfig3 {
        get {
            return this.dIOLineConfig3Field;
        }
        set {
            this.dIOLineConfig3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DIOLineConfig3Specified {
        get {
            return this.dIOLineConfig3FieldSpecified;
        }
        set {
            this.dIOLineConfig3FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public uint HardwareSettlingTime {
        get {
            return this.hardwareSettlingTimeField;
        }
        set {
            this.hardwareSettlingTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HardwareSettlingTimeSpecified {
        get {
            return this.hardwareSettlingTimeFieldSpecified;
        }
        set {
            this.hardwareSettlingTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Channel", IsNullable=false)]
    public SLSCModuleChannel[] Channels {
        get {
            return this.channelsField;
        }
        set {
            this.channelsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SLSCModuleChannel {
    
    private string nameField;
    
    private byte switchNumberField;
    
    private bool switchNumberFieldSpecified;
    
    private byte thresholdNumberField;
    
    private bool thresholdNumberFieldSpecified;
    
    private byte faultNumberField;
    
    private bool faultNumberFieldSpecified;
    
    private byte lEDNumberField;
    
    private bool lEDNumberFieldSpecified;
    
    private byte channelNumberField;
    
    private bool channelNumberFieldSpecified;
    
    private byte resistanceNumberField;
    
    private bool resistanceNumberFieldSpecified;
    
    private double defaultValueField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public byte SwitchNumber {
        get {
            return this.switchNumberField;
        }
        set {
            this.switchNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SwitchNumberSpecified {
        get {
            return this.switchNumberFieldSpecified;
        }
        set {
            this.switchNumberFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ThresholdNumber {
        get {
            return this.thresholdNumberField;
        }
        set {
            this.thresholdNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ThresholdNumberSpecified {
        get {
            return this.thresholdNumberFieldSpecified;
        }
        set {
            this.thresholdNumberFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte FaultNumber {
        get {
            return this.faultNumberField;
        }
        set {
            this.faultNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FaultNumberSpecified {
        get {
            return this.faultNumberFieldSpecified;
        }
        set {
            this.faultNumberFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte LEDNumber {
        get {
            return this.lEDNumberField;
        }
        set {
            this.lEDNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LEDNumberSpecified {
        get {
            return this.lEDNumberFieldSpecified;
        }
        set {
            this.lEDNumberFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ChannelNumber {
        get {
            return this.channelNumberField;
        }
        set {
            this.channelNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ChannelNumberSpecified {
        get {
            return this.channelNumberFieldSpecified;
        }
        set {
            this.channelNumberFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ResistanceNumber {
        get {
            return this.resistanceNumberField;
        }
        set {
            this.resistanceNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ResistanceNumberSpecified {
        get {
            return this.resistanceNumberFieldSpecified;
        }
        set {
            this.resistanceNumberFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double DefaultValue {
        get {
            return this.defaultValueField;
        }
        set {
            this.defaultValueField = value;
        }
    }
}
